### ISSUE TITLE
Support new GTag G-XXX code

### ISSUE THREAD

**Issue by dvitcompte** [SkizNet/mediawiki-GTag#1]
Hello,

I had to change the line
`if ( $gaId === '' || !preg_match( '/^UA-[0-9]+-[0-9]+$/', $gaId ) ) {`
to
`if ( $gaId === '' || !preg_match( '/^G-[0-9A-Z]+$/', $gaId ) ) {`

in file GTagHook.php in order to make it work with a GTag code.

Thank for your extension.

Best regards,

**Comment by skizzerz** [comment]
Thanks, looks like the G-XXXXXX form is for App+Web properties; I'll get support added for that id format as well shortly! I do still need the UA-XXXXXX-X format as well, since that id format is still used for Web-only properties.
